spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000

cloudflare:
  r2:
    access-key: ${R2_ACCESS_KEY}
    secret-key: ${R2_SECRET_KEY}
    bucket: ${R2_BUCKET}
    endpoint: ${R2_ENDPOINT}

youtube:
  api:
    key: ${YOUTUBE_API_KEY}
  featured-channel-ids: "UCcQTRi69dsVYHN3exePtZ1A,UCF4Wxdo3inmxP-Y59wXDsFw,UCkinYTS9IHqOEwR1Sze2JTw,UCsU-I-vHLiaMfV_ceaYz5rQ,UChlgI3UHCOnwUGzWzbJ3H5w"

ai-pipeline:
  base-url: ${AI_PIPELINE_URL:http://localhost:8000}

server:
  port: 8080

python:
  base-url: ${PYTHON_BASE_URL:http://localhost:8000}